# Generated by Django 4.2.7 on 2023-11-30 13:07

from django.db import migrations, models
import voiceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_voice",
            name="voice_file",
            field=models.FileField(upload_to=voiceapp.models.getFileName),
        ),
    ]
