# Generated by Django 4.2.7 on 2023-11-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0005_user_voice_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_voice",
            name="user",
        ),
    ]
