# Generated by Django 4.2.7 on 2023-11-30 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voiceapp", "0007_user_voice_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_voice",
            name="user",
        ),
        migrations.AlterField(
            model_name="user_voice",
            name="to_user_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
