# Generated by Django 4.2.7 on 2023-11-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0008_remove_user_voice_user_alter_user_voice_to_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_voice",
            name="to_user_name",
            field=models.CharField(max_length=150),
        ),
    ]
