# Generated by Django 4.2.7 on 2023-11-30 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voiceapp", "0009_alter_user_voice_to_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_voice",
            name="from_user_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="from_user_name",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user_voice",
            name="to_user_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="to_user_name",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
