# Generated by Django 4.2.7 on 2023-12-06 13:25

from django.db import migrations, models
import voiceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0010_alter_user_voice_from_user_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=voiceapp.models.getFileName
                    ),
                ),
                ("description", models.TextField(max_length=2500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
