# Generated by Django 4.2.7 on 2023-12-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0013_rename_name_audio_audio_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Catagory_Audio",
        ),
    ]
