# Generated by Django 4.2.7 on 2023-12-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0014_delete_catagory_audio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Audio",
        ),
    ]
