# Generated by Django 4.2.7 on 2023-12-06 14:42

from django.db import migrations, models
import django.db.models.deletion
import voiceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0015_delete_audio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catagory",
            old_name="Catagory_name",
            new_name="name",
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=voiceapp.models.getFileName
                    ),
                ),
                ("description", models.TextField(max_length=2500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Catagory_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Catagory_name",
                        to="voiceapp.catagory",
                    ),
                ),
            ],
        ),
    ]
