# Generated by Django 4.2.7 on 2023-12-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0016_rename_catagory_name_catagory_name_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="image",
        ),
    ]
