# Generated by Django 5.0 on 2023-12-11 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0020_alter_audio_catagory_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio_user",
            name="Audio_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="voiceapp.audio"
            ),
        ),
        migrations.AlterField(
            model_name="audio_user",
            name="User_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
