# Generated by Django 5.0 on 2023-12-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("voiceapp", "0023_audio_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio_group",
            name="Group_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="auth.group"
            ),
        ),
    ]
