# Generated by Django 5.0 on 2024-01-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voiceapp", "0025_audio_attribuemodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fichiers_reçusmodel",
            options={"verbose_name_plural": "Fichiers reçus"},
        ),
    ]
